### ISSUE TITLE
Bug - version .: django_fluent_dashboard-0.5.3 ...

### ISSUE THREAD

**Issue by Ademir-Francisco-da-Silva** [django-fluent/django-fluent-dashboard#15]
Please verify in your file  "../django-fluent-dashboard/fluent_dashboard/appgroups.py"  in the lines 6 and 83 as follow ...

from future.utils import iteritems
for (name, order) in iteritems(appsettings.FLUENT_DASHBOARD_CMS_MODEL_ORDER):

To solve that "bug" ..., i have chaged them as below ...

( commented ) # from future.utils import iteritems
for name, order in appsettings.FLUENT_DASHBOARD_CMS_MODEL_ORDER.iteritems():

And everything have worked well again ...

**Comment by vdboor** [comment]
Which version of python-future are you using?
